models/UserBetCancel.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "user_bet_cancel".
 *
 * @property integer $id
 * @property integer $bet_id
 * @property integer $status
 * @property string $created_by
 * @property string $created
 * @property string $modified
 */
class UserBetCancel extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_bet_cancel';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bet_id', 'status', 'created_by'], 'required'],
            [['status'], 'integer'],
            [['created', 'modified'], 'safe'],
            [['created_by'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'bet_id' => 'Bet ID',
            'status' => 'Status',
            'created_by' => 'Created By',
            'created' => 'Created',
            'modified' => 'Modified',
        ];
    }

    public function updateBets($data, $created_by) {
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        try{
            $data1 = explode(',', $data);
            foreach($data1 as $value){
               
                //$created_by = "Ronoh";
                $status = 24;
               
                $sql1 = "INSERT INTO user_bet_cancel(bet_id,status,created_by)  VALUES('$value','$status','$created_by')";
                $connection->createCommand($sql1)->execute();

                // $sql2 = "UPDATE bet SET status = 24 WHERE bet_id = '$value' ";
                // $connection->createCommand($sql2)->execute();
            }

            $transaction->commit();
            return TRUE;
        } catch (Exception $exc) {
            $transaction->rollback();
            return FALSE;
        }
        
    }

     /* public function cancelBet($bet_id) {
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        try{
      
                $status = 24;
               
                $sql = "UPDATE bet SET status = 24 WHERE bet_id = '$bet_id' ";
                $connection->createCommand($sql)->execute();

            $transaction->commit();
            return TRUE;
        } catch (Exception $exc) {
            $transaction->rollback();
            return FALSE;
        }
        */
        
    }
}

controllers/UserBetCancelController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\UserBetCancel;
use frontend\models\UserBetCancelSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserBetCancelController implements the CRUD actions for UserBetCancel model.
 */
class UserBetCancelController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all UserBetCancel models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserBetCancelSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single UserBetCancel model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new UserBetCancel model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserBetCancel();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

                return $this->redirect(['view', 'id' => $model->id]);
            // Cancel Bet
           // $result = $model->cancelBet($model->bet_id);

           /* if($result) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            } */

            
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing UserBetCancel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing UserBetCancel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the UserBetCancel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UserBetCancel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserBetCancel::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionManualcreate() {
        $model = new UserBetCancel();

        if(Yii::$app->request->post()) {

            $model->load(Yii::$app->request->post());
            $data = rtrim($model->bet_id,' ');
            $created_by = $model->created_by;

            
            // $result = $model->updateBets($data, $created_by);

            if($result) {
                $msg = "All bets cancelled successfully.";
                $error = 'success';

                Yii::$app->getSession()->setFlash($error, $msg);

                return $this->redirect(['index']);

            } else {
                return $this->redirect('index.php?r=user-bet-cancel%2Fmanualcreate');
            }
            

        } else {
        return $this->render('manual_create', [
                'model' => $model,
            ]);
        }
    }
}

views/user-bet-cancel/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\UserBetCancel */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-bet-cancel-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'bet_id')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'created_by')->hiddenInput(['value' => 'Ronoh'])->label(false); ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user-bet-cancel/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\UserBetCancelSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-bet-cancel-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'bet_id') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'created_by') ?>

    <?= $form->field($model, 'created') ?>

    <?php // echo $form->field($model, 'modified') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user-bet-cancel/_user_bet_cancel_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\UserBetCancel */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="manual-user-bet-cancel-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'bet_id')->textArea(array('placeholder'=>'Add bet ids here seperated by commas.')) ?>

    <?= $form->field($model, 'created_by')->hiddenInput(['value' => 'Ronoh'])->label(false); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Cancel Bets' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user-bet-cancel/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\UserBetCancel */

$this->title = 'Cancel Bet';
$this->params['breadcrumbs'][] = ['label' => 'Cancel Bets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-bet-cancel-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user-bet-cancel/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\UserBetCancelSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Cancelled Bets';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-bet-cancel-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create', ['create'], ['class' => 'btn btn-success']) ?>
        <a class="btn btn-info" href="<?php echo Url::to(['user-bet-cancel/manualcreate']) ?>">Manually Cancel Bets</a>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'bet_id',
            'status',
            'created_by',
            'created',
            'modified',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/user-bet-cancel/manual_create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\UserBetCancel */

$this->title = 'Cancel Bets';
$this->params['breadcrumbs'][] = ['label' => 'User Bet Cancels', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-bet-cancel-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_user_bet_cancel_form', [
        'model' => $model,
    ]) ?>

</div>

views/user-bet-cancel/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\UserBetCancel */

$this->title = 'Update Bet Cancelled: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'User Bet Cancels', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-bet-cancel-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user-bet-cancel/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\UserBetCancel */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Cancelled Bets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-bet-cancel-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'bet_id',
            'status',
            'created_by',
            'created',
            'modified',
        ],
    ]) ?>

</div>