models/JpbonusAward.php
<?php

namespace frontend\models;

use Yii;
use frontend\models\JackpotEvent;

/**
 * This is the model class for table "jpbonus_award".
 *
 * @property integer $id
 * @property integer $jackpot_event_id
 * @property double $jackpot_bonus
 * @property integer $betika_points_bonus
 * @property string $created_by
 * @property string $created
 * @property string $modified
 */
class JpbonusAward extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jpbonus_award';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['jackpot_event_id', 'jackpot_bonus', 'betika_points_bonus', 'created_by'], 'required'],
            [['jackpot_event_id', 'betika_points_bonus'], 'integer'],
            [['jackpot_bonus'], 'number'],
            [['created', 'modified'], 'safe'],
            [['created_by'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'jackpot_event_id' => 'Jackpot Event ID',
            'jackpot_bonus' => 'Jackpot Bonus',
            'betika_points_bonus' => 'Betika Points Bonus',
            'created_by' => 'Created By',
            'created' => 'Created',
            'modified' => 'Modified',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJackpotEvents()
    {
        return $this->hasMany(JackpotEvent::className(), ['jackpot_event' => 'jackpot_event_id']);
    }

     public function awardJackpotBonus($jackpot_event_id, $jackpot_bonus, $betika_points_bonus, $created_by) {
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();
        try{
               
                $sql = "INSERT INTO jpbonus_award(jackpot_event_id,jackpot_bonus,betika_points_bonus,created_by)  VALUES('$jackpot_event_id','$jackpot_bonus','$betika_points_bonus','$created_by')";
                
                $connection->createCommand($sql)->execute();

                $transaction->commit();
                
                return TRUE;
        
        } catch (Exception $exc) {
            $transaction->rollback();
            return FALSE;
        }
        
    }
}

controllers/JpbonusAwardController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\JpbonusAward;
use frontend\models\JpbonusAwardSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * JpbonusAwardController implements the CRUD actions for JpbonusAward model.
 */
class JpbonusAwardController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all JpbonusAward models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new JpbonusAwardSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single JpbonusAward model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new JpbonusAward model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new JpbonusAward();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing JpbonusAward model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing JpbonusAward model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the JpbonusAward model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return JpbonusAward the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = JpbonusAward::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAwardjackpotbonus() {
        $model = new JpbonusAward();

        if(Yii::$app->request->post()) {

            $model->load(Yii::$app->request->post());
            
            $result = $model->awardJackpotBonus($model->jackpot_event_id, $model->jackpot_bonus, $model->betika_points_bonus, $model->created_by);

            if($result) {
                $msg = "Jackpot Bonus Awarded Successfully.";
                $error = 'success';

                Yii::$app->getSession()->setFlash($error, $msg);

                return $this->redirect(['index']);

            } else {
                return $this->redirect('index.php?r=jpbonus-award%2Fawardjackpotbonus');
            }
            

        } else {
        return $this->render('award_jackpot_bonus', [
                'model' => $model,
            ]);
        }
    }


}

views/jpbonus-award/_award_jackpot_bonus_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\JackpotEvent;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model frontend\models\JpbonusAward */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="jpbonus-award-form">

    <?php $form = ActiveForm::begin(); ?>
    <label>Jackpot Event</label>
    <?= Html::activeDropDownList($model, 'jackpot_event_id',
      ArrayHelper::map(JackpotEvent::find()->all(), 'jackpot_event_id', 'jackpot_name'), ['class'=>'form-control', 'label'=>'Jackpot Eent']) ?>
     <br>

    <?= $form->field($model, 'jackpot_bonus')->textInput() ?>

    <?= $form->field($model, 'betika_points_bonus')->textInput() ?>

    <?= $form->field($model, 'created_by')->hiddenInput(['value' => 'Ronoh'])->label(false); ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Award Bonus' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/jpbonus-award/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\JpbonusAward */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="jpbonus-award-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'jackpot_event_id')->textInput() ?>

    <?= $form->field($model, 'jackpot_bonus')->textInput() ?>

    <?= $form->field($model, 'betika_points_bonus')->textInput() ?>

    <?= $form->field($model, 'created_by')->hiddenInput(['value' => 'Ronoh'])->label(false); ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/jpbonus-award/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\JpbonusAwardSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="jpbonus-award-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'jackpot_event_id') ?>

    <?= $form->field($model, 'jackpot_bonus') ?>

    <?= $form->field($model, 'betika_points_bonus') ?>

    <?= $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created') ?>

    <?php // echo $form->field($model, 'modified') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/jpbonus-award/award_jackpot_bonus.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\UserBetCancel */

$this->title = 'Award Jackpot Bonus';
$this->params['breadcrumbs'][] = ['label' => 'Award Jackpot Bonus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="award-jackpot-bonus">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_award_jackpot_bonus_form', [
        'model' => $model,
    ]) ?>

</div>

views/jpbonus-award/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\JpbonusAward */

$this->title = 'Create Jpbonus Award';
$this->params['breadcrumbs'][] = ['label' => 'Jpbonus Awards', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jpbonus-award-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/jpbonus-award/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use frontend\models\JackpotEvent;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\JpbonusAwardSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Jackpot Bonus Awards';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jpbonus-award-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Jackpot Bonus Award', ['create'], ['class' => 'btn btn-success']) ?>
        <a class="btn btn-info" href="<?php echo Url::to(['jpbonus-award/awardjackpotbonus']) ?>">Manually Award Jackpot Bonus</a>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'jackpot_event_id',
            'jackpot_bonus',
            'betika_points_bonus',
            'created_by',
            'created',
            'modified',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/jpbonus-award/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\JpbonusAward */

$this->title = 'Update Jpbonus Award: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Jpbonus Awards', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="jpbonus-award-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/jpbonus-award/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\JpbonusAward */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Jpbonus Awards', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jpbonus-award-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'jackpot_event_id',
            'jackpot_bonus',
            'betika_points_bonus',
            'created_by',
            'created',
            'modified',
        ],
    ]) ?>

</div>